version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prueba-tecnica-postgres
    environment:
      POSTGRES_DB: prueba_tecnica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prueba-tecnica-network

volumes:
  postgres_data:

networks:
  prueba-tecnica-network:
    driver: bridge
